class_name JCSBinary64
extends RefCounted

## Deterministic RFC 8785 / ECMAScript binary64 serialization.
##
## The conversion keeps the exact IEEE-754 value and its two adjacent
## rounding midpoints as positive base-1e9 integers. Decimal digits are then
## generated by Dragon4-style long division. No engine formatter, JSON
## implementation, process, locale, or external data source participates.

const BIG_BASE: int = 1000000000
const SIGN_MASK: int = -9223372036854775808
const EXPONENT_MASK: int = 0x7ff
const FRACTION_MASK: int = 0x000fffffffffffff

## Returns the JCS number literal, or an empty string for a non-finite value.
## Example: `JCSBinary64.encode(1.5) == "1.5"`.
static func encode(value: float) -> String:
	if is_nan(value) or is_inf(value):
		return ""
	if value == 0.0:
		return "0"
	var bytes := PackedByteArray()
	bytes.resize(8)
	bytes.encode_double(0, value)
	var bits: int = bytes.decode_u64(0)
	var negative := (bits & SIGN_MASK) != 0
	var magnitude_bits: int = bits & 0x7fffffffffffffff
	var exponent_bits: int = int((magnitude_bits >> 52) & EXPONENT_MASK)
	var fraction: int = magnitude_bits & FRACTION_MASK
	var significand: int
	var binary_exponent: int
	if exponent_bits == 0:
		significand = fraction
		binary_exponent = -1074
	else:
		significand = (1 << 52) | fraction
		binary_exponent = exponent_bits - 1023 - 52
	var power_context: Dictionary = {"pow2": [[1]], "pow10": [[1]]}
	var decimal_power := _decimal_power(significand, binary_exponent, power_context)
	var interval := _scaled_interval(significand, binary_exponent, exponent_bits, fraction, power_context)
	var magnitude := _dragon_shortest(interval, decimal_power, (significand & 1) == 0)
	if magnitude.is_empty():
		return ""
	return ("-" if negative else "") + magnitude

## Test/codec support for literal bit-pattern vectors. The bytes are copied so
## callers cannot mutate an internal buffer.
## Example: `var value := JCSBinary64.decode_double(JCSBinary64.encode_u64(bits))`.
static func decode_double(bytes: PackedByteArray) -> float:
	if bytes.size() != 8:
		return 0.0
	return PackedByteArray(bytes).decode_double(0)

## Returns an eight-byte IEEE-754 bit-pattern buffer.
## Example: `var bytes := JCSBinary64.encode_u64(0x3ff0000000000000)`.
static func encode_u64(bits: int) -> PackedByteArray:
	var bytes := PackedByteArray()
	bytes.resize(8)
	bytes.encode_u64(0, bits)
	return bytes

static func _scaled_interval(significand: int, binary_exponent: int, exponent_bits: int, fraction: int, power_context: Dictionary) -> Dictionary:
	var lower_margin: int = 1
	var upper_margin: int = 1
	var common_exponent: int
	var scaled_value: Array
	if exponent_bits > 1 and fraction == 0:
		# A normalized power of two has half the spacing below it.
		common_exponent = binary_exponent - 2
		scaled_value = _bi_mul_small(_bi_from_int(significand), 4)
		upper_margin = 2
	else:
		common_exponent = binary_exponent - 1
		scaled_value = _bi_mul_small(_bi_from_int(significand), 2)
	var denominator: Array = [1]
	var lower: Array = [lower_margin]
	var upper: Array = [upper_margin]
	if common_exponent >= 0:
		var factor := _pow2(common_exponent, power_context)
		scaled_value = _bi_mul(scaled_value, factor)
		lower = _bi_mul(lower, factor)
		upper = _bi_mul(upper, factor)
	else:
		denominator = _pow2(-common_exponent, power_context)
	return {"value": scaled_value, "lower": lower, "upper": upper, "denominator": denominator}

static func _decimal_power(significand: int, binary_exponent: int, power_context: Dictionary) -> int:
	var binary := _binary_ratio(significand, binary_exponent, power_context)
	var decimal_power := -324
	for candidate in range(-324, 309):
		var power := _pow10(absi(candidate), power_context)
		var right_num: Array = power if candidate >= 0 else [1]
		var right_den: Array = [1] if candidate >= 0 else power
		if _rational_compare(binary["num"], binary["den"], right_num, right_den) < 0:
			break
		decimal_power = candidate
	return decimal_power

static func _binary_ratio(significand: int, binary_exponent: int, power_context: Dictionary) -> Dictionary:
	var numerator := _bi_from_int(significand)
	if binary_exponent >= 0:
		numerator = _bi_mul(numerator, _pow2(binary_exponent, power_context))
		return {"num": numerator, "den": [1]}
	return {"num": numerator, "den": _pow2(-binary_exponent, power_context)}

static func _dragon_shortest(interval: Dictionary, decimal_power: int, even_significand: bool) -> String:
	var numerator: Array = interval["value"]
	var lower_margin: Array = interval["lower"]
	var upper_margin: Array = interval["upper"]
	var denominator: Array = interval["denominator"]
	while _bi_cmp(numerator, denominator) < 0:
		numerator = _bi_mul_small(numerator, 10)
		lower_margin = _bi_mul_small(lower_margin, 10)
		upper_margin = _bi_mul_small(upper_margin, 10)
	while _bi_cmp(numerator, _bi_mul_small(denominator, 10)) >= 0:
		denominator = _bi_mul_small(denominator, 10)

	var digits := ""
	for _index in range(17):
		var digit := 0
		while digit < 9 and _bi_cmp(numerator, denominator) >= 0:
			numerator = _bi_sub(numerator, denominator)
			digit += 1
		digits += str(digit)
		var lower_ok := _bi_cmp(numerator, lower_margin) < 0 or (even_significand and _bi_cmp(numerator, lower_margin) == 0)
		var remainder_to_upper := _bi_sub(denominator, numerator)
		var upper_ok := _bi_cmp(remainder_to_upper, upper_margin) < 0 or (even_significand and _bi_cmp(remainder_to_upper, upper_margin) == 0)
		if lower_ok or upper_ok:
			if lower_ok and upper_ok:
				var twice_remainder := _bi_mul_small(numerator, 2)
				var midpoint := _bi_cmp(twice_remainder, denominator)
				if midpoint > 0 or (midpoint == 0 and (digit & 1) != 0):
					digits = _increment_decimal_digits(digits)
			elif upper_ok:
				digits = _increment_decimal_digits(digits)
			return _format_digits(digits, decimal_power)
		numerator = _bi_mul_small(numerator, 10)
		lower_margin = _bi_mul_small(lower_margin, 10)
		upper_margin = _bi_mul_small(upper_margin, 10)
	return ""

static func _increment_decimal_digits(digits: String) -> String:
	var characters := digits.to_ascii_buffer()
	var index := characters.size() - 1
	while index >= 0 and characters[index] == 57:
		characters[index] = 48
		index -= 1
	if index < 0:
		return "1" + characters.get_string_from_ascii()
	characters[index] += 1
	return characters.get_string_from_ascii()

static func _format_digits(digits: String, decimal_power: int) -> String:
	var trimmed := digits
	while trimmed.length() > 1 and trimmed.ends_with("0"):
		trimmed = trimmed.left(trimmed.length() - 1)
		decimal_power += 1
	# `decimal_power` is the exponent of the first emitted digit. Convert it
	# to the exponent after the significant digits so the interval contract's
	# n = digits.length + decimal_power is explicit.
	var decimal_power_after_digits := decimal_power - trimmed.length() + 1
	var n := trimmed.length() + decimal_power_after_digits
	if n > -6 and n <= 21:
		var point := n
		if point <= 0:
			return "0." + "0".repeat(-point) + trimmed
		if point >= trimmed.length():
			return trimmed + "0".repeat(point - trimmed.length())
		return trimmed.substr(0, point) + "." + trimmed.substr(point)
	var mantissa := trimmed.substr(0, 1)
	if trimmed.length() > 1:
		mantissa += "." + trimmed.substr(1)
	var exponent := n - 1
	var exponent_sign := "+" if exponent >= 0 else "-"
	return mantissa + "e" + exponent_sign + str(absi(exponent))

static func _rational_compare(left_num: Array, left_den: Array, right_num: Array, right_den: Array) -> int:
	return _bi_cmp(_bi_mul(left_num, right_den), _bi_mul(right_num, left_den))

static func _pow2(power: int, power_context: Dictionary) -> Array:
	var powers: Array = power_context["pow2"]
	while powers.size() <= power:
		powers.append(_bi_mul_small(powers[powers.size() - 1], 2))
	return powers[power].duplicate()

static func _pow10(power: int, power_context: Dictionary) -> Array:
	var powers: Array = power_context["pow10"]
	while powers.size() <= power:
		powers.append(_bi_mul_small(powers[powers.size() - 1], 10))
	return powers[power].duplicate()

static func _bi_from_int(value: int) -> Array:
	if value <= 0:
		return [0]
	var result: Array = []
	var remaining := value
	while remaining > 0:
		var split := _bi_divmod_base(remaining)
		result.append(split[1])
		remaining = split[0]
	return result

## Returns an exact quotient/remainder pair for a non-negative 64-bit value.
## The floating division is only a bounded seed; integer correction makes the
## result exact even when the source exceeds binary64's integer precision.
static func _bi_divmod_base(value: int) -> Array:
	var remainder := value % BIG_BASE
	var target := value - remainder
	var quotient := int(value / BIG_BASE)
	while quotient * BIG_BASE > target:
		quotient -= 1
	while (quotient + 1) * BIG_BASE <= target:
		quotient += 1
	return [quotient, remainder]

static func _bi_cmp(left: Array, right: Array) -> int:
	var left_size := _bi_size(left)
	var right_size := _bi_size(right)
	if left_size != right_size:
		return -1 if left_size < right_size else 1
	for index in range(left_size - 1, -1, -1):
		var left_digit: int = left[index]
		var right_digit: int = right[index]
		if left_digit != right_digit:
			return -1 if left_digit < right_digit else 1
	return 0

static func _bi_size(value: Array) -> int:
	var size := value.size()
	while size > 1 and int(value[size - 1]) == 0:
		size -= 1
	return size

static func _bi_add_small(value: Array, amount: int) -> Array:
	var result: Array = value.duplicate()
	var carry := amount
	var index := 0
	while carry > 0:
		if index >= result.size():
			result.append(0)
		var total: int = int(result[index]) + carry
		var split := _bi_divmod_base(total)
		result[index] = split[1]
		carry = split[0]
		index += 1
	return result

static func _bi_mul_small(value: Array, factor: int) -> Array:
	if factor == 0 or _bi_cmp(value, [0]) == 0:
		return [0]
	var result: Array = []
	var carry: int = 0
	for digit_value in value:
		var product: int = int(digit_value) * factor + carry
		var split := _bi_divmod_base(product)
		result.append(split[1])
		carry = split[0]
	while carry > 0:
		var split := _bi_divmod_base(carry)
		result.append(split[1])
		carry = split[0]
	return result

static func _bi_mul(left: Array, right: Array) -> Array:
	if _bi_cmp(left, [0]) == 0 or _bi_cmp(right, [0]) == 0:
		return [0]
	var result: Array = []
	result.resize(left.size() + right.size() + 1)
	for index in range(result.size()):
		result[index] = 0
	for left_index in range(left.size()):
		var carry: int = 0
		for right_index in range(right.size()):
			var result_index := left_index + right_index
			var product: int = int(result[result_index]) + int(left[left_index]) * int(right[right_index]) + carry
			var split := _bi_divmod_base(product)
			result[result_index] = split[1]
			carry = split[0]
		var carry_index := left_index + right.size()
		while carry > 0:
			var sum: int = int(result[carry_index]) + carry
			var split := _bi_divmod_base(sum)
			result[carry_index] = split[1]
			carry = split[0]
			carry_index += 1
	return result

static func _bi_sub(left: Array, right: Array) -> Array:
	var result: Array = []
	var borrow: int = 0
	for index in range(left.size()):
		var difference: int = int(left[index]) - (int(right[index]) if index < right.size() else 0) - borrow
		if difference < 0:
			difference += BIG_BASE
			borrow = 1
		else:
			borrow = 0
		result.append(difference)
	while result.size() > 1 and int(result[result.size() - 1]) == 0:
		result.pop_back()
	return result
